model:
  squeeze_kwargs:
    input_channels: 11 # 8
pass_keys:
  - depth
  - labels_embed
  - rgb
  - rgb_mask
  - mask
gt_keys:
  - rgb_mask
  - labels
embed:
  num_embeddings: 26
  embedding_dim: 5
  max_norm: 1
embed_channel: labels
store_dir: drgbl