train:
  folder: /mnt/data/vras/Reflectance/data/TrainRef
  name: gta-train
  ext: .npy
  shuffle: True
  keep_ram: True
val:
  folder: /mnt/data/vras/Reflectance/data/Validation
  name: gta-val
  ext: .npy
  shuffle: False
  keep_ram: True
train_loader:
  batch_size: 24
  shuffle: True
  num_workers: 4
  pin_memory: True
val_loader:
  batch_size: 24
  shuffle: False
  num_workers: 4
  pin_memory: True
  