val:
  channels:
    - name: labels
      start: 4
      end: 5
      retype: i8
      squeeze: True
train:
  channels:
    - name: labels
      start: 4
      end: 5
      retype: i8
      squeeze: True